---
image: python

stages:
  - test
  - build
  - release

before_script:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install tox poetry coveralls pyyaml tomli

style:
  image: python:3.11
  stage: test
  script: tox -e style

python38:
  image: python:3.8
  stage: test
  script: tox -e py38

python39:
  image: python:3.9
  stage: test
  script: tox -e py39

python310:
  image: python:3.10
  stage: test
  script: tox -e py310

python311:
  image: python:3.11
  stage: test
  script: tox -e py311

coverage:
  image: python:3.11
  stage: test
  script:
    - tox -e coverage
    - coveralls
