---
image: python

stages:
  - test
  - build
  - release

before_script:
  - curl -O https://bootstrap.pypa.io/get-pip.py
  - python get-pip.py
  - pip install tox poetry python-coveralls coverage

python35:
  image: python:3.5
  stage: test
  script: tox -e py35

python36:
  image: python:3.6
  stage: test
  script: tox -e py36

python37:
  image: python:3.7
  stage: test
  script: tox -e py37

python38:
  image: python:3.8
  stage: test
  script: tox -e py38

coverage:
  image: python:3.7
  stage: test
  script:
    - tox -e coverage
    - coveralls
